name: ToDoList
description: Material To Do App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  auto_size_text: ^3.0.0
  path_provider: ^2.0.9
  fluttertoast: ^8.0.8
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true